basePath: /api/v1
definitions:
  kbtuspace-backend_internal_models.RegisterInput:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - password
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is the central API for the UniHub university ecosystem.
  title: UniHub API
  version: "1.0"
paths:
  /auth/register:
    post:
      consumes:
      - application/json
      description: Creates a new student or user
      parameters:
      - description: Registration info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/kbtuspace-backend_internal_models.RegisterInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "409":
          description: Conflict
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Register a new user
      tags:
      - auth
securityDefinitions:
  BearerAuth:
    description: Type "Bearer " followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
